config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :contacts
  resources :link_playlist_videos
  resources :musics
  resources :infos
  resources :scripts
  root to: 'home#index'

  resources :contacts do
    member do
      patch "change_avatar"
      get "cartao"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/script.rb
class Script < ApplicationRecord
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy]

  # GET /scripts
  # GET /scripts.json
  def index
    @scripts = Script.all
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { render :show, status: :ok, location: @script }
      else
        format.html { render :edit }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: 'Script was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def script_params
      params.require(:script).permit(:title, :content, :url_image)
    end
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/scripts/_form.html.erb
<%= form_with(model: script, local: true) do |form| %>
  <% if script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<h1>Editing Script</h1>

<%= render 'form', script: @script %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

app/views/scripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scripts</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Url image</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @scripts.each do |script| %>
    <tr>
      <td><%= script.title %></td>
      <td><%= script.content %></td>

      <% begin %>
        <td><%= image_tag script.url_image, width: 50, height: 50 %></td>
      <% rescue %>
        <td><%= image_tag 'https://developers.google.com/maps/documentation/streetview/images/error-image-generic.png', width: 50, height: 50 %></td>
      <% end %>

      <td><%= link_to 'Show', script %></td>
      <td><%= link_to 'Edit', edit_script_path(script) %></td>
      <td><%= link_to 'Destroy', script, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Script', new_script_path %>

app/views/scripts/new.html.erb
<h1>New Script</h1>

<%= render 'form', script: @script %>

<%= link_to 'Back', scripts_path %>

app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @script.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @script.content %>
</p>

<p>
  <strong>Url image:</strong>
  <%= @script.url_image %>
</p>

<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>