config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :contacts
  resources :link_playlist_videos
  resources :musics
  resources :infos
  resources :scripts
  root to: 'home#index'

  resources :contacts do
    member do
      patch "change_avatar"
      get "cartao"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/link_playlist_video.rb
class LinkPlaylistVideo < ApplicationRecord
end

app/controllers/link_playlist_videos_controller.rb
class LinkPlaylistVideosController < ApplicationController
  before_action :set_link_playlist_video, only: [:show, :edit, :update, :destroy]

  # GET /link_playlist_videos
  # GET /link_playlist_videos.json
  def index
    @link_playlist_videos = LinkPlaylistVideo.all
  end

  # GET /link_playlist_videos/1
  # GET /link_playlist_videos/1.json
  def show
  end

  # GET /link_playlist_videos/new
  def new
    @link_playlist_video = LinkPlaylistVideo.new
  end

  # GET /link_playlist_videos/1/edit
  def edit
  end

  # POST /link_playlist_videos
  # POST /link_playlist_videos.json
  def create
    @link_playlist_video = LinkPlaylistVideo.new(link_playlist_video_params)

    respond_to do |format|
      if @link_playlist_video.save
        format.html { redirect_to @link_playlist_video, notice: 'Link playlist video was successfully created.' }
        format.json { render :show, status: :created, location: @link_playlist_video }
      else
        format.html { render :new }
        format.json { render json: @link_playlist_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /link_playlist_videos/1
  # PATCH/PUT /link_playlist_videos/1.json
  def update
    respond_to do |format|
      if @link_playlist_video.update(link_playlist_video_params)
        format.html { redirect_to @link_playlist_video, notice: 'Link playlist video was successfully updated.' }
        format.json { render :show, status: :ok, location: @link_playlist_video }
      else
        format.html { render :edit }
        format.json { render json: @link_playlist_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /link_playlist_videos/1
  # DELETE /link_playlist_videos/1.json
  def destroy
    @link_playlist_video.destroy
    respond_to do |format|
      format.html { redirect_to link_playlist_videos_url, notice: 'Link playlist video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link_playlist_video
      @link_playlist_video = LinkPlaylistVideo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_playlist_video_params
      params.require(:link_playlist_video).permit(:link)
    end
end

app/helpers/link_playlist_videos_helper.rb
module LinkPlaylistVideosHelper
end

app/views/link_playlist_videos/_form.html.erb
<%= form_with(model: link_playlist_video, local: true) do |form| %>
  <% if link_playlist_video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link_playlist_video.errors.count, "error") %> prohibited this link_playlist_video from being saved:</h2>

      <ul>
      <% link_playlist_video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/link_playlist_videos/edit.html.erb
<h1>Editing Link Playlist Video</h1>

<%= render 'form', link_playlist_video: @link_playlist_video %>

<%= link_to 'Show', @link_playlist_video %> |
<%= link_to 'Back', link_playlist_videos_path %>

app/views/link_playlist_videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Link Playlist Videos</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @link_playlist_videos.each do |link_playlist_video| %>
      <tr>
        <td><%= link_playlist_video.link %></td>
        <td><%= link_to 'Show', link_playlist_video %></td>
        <td><%= link_to 'Edit', edit_link_playlist_video_path(link_playlist_video) %></td>
        <td><%= link_to 'Destroy', link_playlist_video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link Playlist Video', new_link_playlist_video_path %>

app/views/link_playlist_videos/new.html.erb
<h1>New Link Playlist Video</h1>

<%= render 'form', link_playlist_video: @link_playlist_video %>

<%= link_to 'Back', link_playlist_videos_path %>

app/views/link_playlist_videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @link_playlist_video.link %>
</p>

<%= link_to 'Edit', edit_link_playlist_video_path(@link_playlist_video) %> |
<%= link_to 'Back', link_playlist_videos_path %>