config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :contacts
  resources :link_playlist_videos
  resources :musics
  resources :infos
  resources :scripts
  root to: 'home#index'

  resources :contacts do
    member do
      patch "change_avatar"
      get "cartao"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  before_create :set_cloudinary_code

  def set_cloudinary_code
    self.cloudinary_code = self.avatar.public_id
  end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy, :change_avatar]


  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html {redirect_to @contact, notice: 'Contact was successfully created.'}
        format.json {render :show, status: :created, location: @contact}
      else
        format.html {render :new}
        format.json {render json: @contact.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html {redirect_to @contact, notice: 'Contact was successfully updated.'}
        format.json {render :show, status: :ok, location: @contact}
      else
        format.html {render :edit}
        format.json {render json: @contact.errors, status: :unprocessable_entity}
      end
    end
  end

  def change_avatar
    # binding.pry
    if params[:contact][:avatar].present?
      if @contact.avatar.present?
        # code_antigo = @user.cloudinary_code || "toauth_avatar_#{@user.cpf}"
        # Cloudinary::Uploader.destroy(code_antigo)
        Cloudinary::Uploader.destroy(@contact.cloudinary_code)
      end
      # @user.cloudinary_code = "toauth_avatar_#{@user.cpf}_#{DateTime.now.to_i}"
      # Cloudinary::Uploader.upload(params[:user][:photo], public_id: "#{@user.cloudinary_code}", invalidate: true)
      public_id = Cloudinary::Uploader.upload(params[:contact][:avatar], public_id: "#{@contact.cloudinary_code}", invalidate: true)
      @contact.avatar_updated = Cloudinary::Utils.cloudinary_url(public_id["public_id"], width: 100, height: 100, crop: :fill)
      @contact.save
    end
    redirect_to @contact
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html {redirect_to contacts_url, notice: 'Contact was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:description, :number, :email, :avatar)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
  <tr>
    <th>Description</th>
    <th>Number</th>
    <th>Email</th>
    <th>Link image</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.description %></td>
      <td><%= contact.number %></td>
      <td><%= contact.email %></td>

      <td>
        <% if contact.avatar_updated.present? %>
          <%= image_tag contact.avatar_updated, width: 50, height: 50 %>
        <% else %>
          <%= image_tag contact.avatar_url, width: 50, height: 50 %>
        <% end %>
      </td>

      <td><%= link_to 'Show', contact %></td>
      <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
      <td><%= link_to 'Destroy', contact, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @contact.description %>
</p>

<p>
  <strong>Number:</strong>
  <%= @contact.number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <% if @contact.avatar_updated.present? %>
    <%= image_tag @contact.avatar_updated, width: 50, height: 50 %>
  <% else %>
    <%= image_tag @contact.avatar_url, width: 50, height: 50 %>
  <% end %>
</p>
<%= form_for @contact, url: change_avatar_contact_path(@contact) do |f| %>
  <strong>Atualizar foto</strong>
  <%= f.file_field :avatar %>
  <%= f.submit "Enviar", class: "btn teal" %>
<% end %>
<br>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>