config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :contacts
  resources :link_playlist_videos
  resources :musics
  resources :infos
  resources :scripts
  root to: 'home#index'

  resources :contacts do
    member do
      patch "change_avatar"
      get "cartao"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/music.rb
class Music < ApplicationRecord
  def photo_url
    if self.photo.present?
      self.photo.sub! 'http://', 'https://'
    else
      'https://toauth.seplan.to.gov.br/mosaicpro/images/default-avatar.png'
    end
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  # before_action :set_img_music, only: [:create]

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # def set_img_music
  #   if params[:music][:photo].present?
  #     if @music.photo.present?
  #       code_antigo = @user.cloudinary_code || "toauth_avatar_#{@user.cpf}"
  #       Cloudinary::Uploader.destroy(code_antigo)
  #     end
  #     @user.cloudinary_code = "toauth_avatar_#{@user.cpf}_#{DateTime.now.to_i}"
  #     Cloudinary::Uploader.upload(params[:user][:photo], public_id: "#{@user.cloudinary_code}", invalidate: true)
  #     @user.photo = Cloudinary::Utils.cloudinary_url("#{@user.cloudinary_code}", width: 100, height: 100, crop: :fill, gravity: :face)
  #     @user.save
  #   end
  #   redirect_to root_path
  # end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    # binding.pry
    #
    # if params[:photo].present?
    #   preloaded = Cloudinary::PreloadedFile.new(params[:photo])
    #   raise "Invalid upload signature" if !preloaded.valid?
    #   binding.pry
    #   @music.photo = preloaded.identifier
    # end

    respond_to do |format|
      if @music.save
        format.html {redirect_to @music, notice: 'Music was successfully created.'}
        format.json {render :show, status: :created, location: @music}
      else
        format.html {render :new}
        format.json {render json: @music.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html {redirect_to @music, notice: 'Music was successfully updated.'}
        format.json {render :show, status: :ok, location: @music}
      else
        format.html {render :edit}
        format.json {render json: @music.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html {redirect_to musics_url, notice: 'Music was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_music
    @music = Music.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def music_params
    params.require(:music).permit(:title, :artist, :lyric, :photo)
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= form_with(model: music, local: true) do |form| %>
  <% if music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :lyric %>
    <%= form.text_field :lyric %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :url_image %>
    <%#= form.text_field :url_image %>
<!--  </div>-->

  <div class="field">
    <%= form.label :photo, "Foto" %>
    <%= form.cl_image_upload :photo  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Musics</h1>

<%= cl_image_tag("samples/landscapes/nature-mountains.jpg", :width=>100, :crop=>"scale") %>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Lyric</th>
    <th>Url image</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @musics.each do |music| %>
    <tr>
      <td><%= music.title %></td>
      <td><%= music.artist %></td>
      <td><%= music.lyric %></td>

      <%# begin %>
      <!--        <td><%#= image_tag music.url_image, width: 50, height: 50 %></td>-->
      <%# rescue %>
      <!--        <td><%#= image_tag 'https://developers.google.com/maps/documentation/streetview/images/error-image-generic.png', width: 50, height: 50 %></td>-->
      <%# end %>
      <td><%= image_tag 'https://developers.google.com/maps/documentation/streetview/images/error-image-generic.png', width: 50, height: 50 %></td>

      <td><%= link_to 'Show', music %></td>
      <td><%= link_to 'Edit', edit_music_path(music) %></td>
      <td><%= link_to 'Destroy', music, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

<!--<script>-->

<!--    var Notifications = {-->
<!--        requestPermission: function(callback) {-->
<!--            window.webkitNotifications.requestPermission(callback);-->
<!--        }-->
<!--    };-->

<!--    $(function() {-->
<!--        $('#click-me').click(function() {-->
<!--            Notifications.requestPermission(function() {-->
<!--                alert('Permissão concedida');-->
<!--            })-->
<!--        });-->
<!--    });-->


<!--</script>-->

app/views/musics/new.html.erb
<h1>New Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @music.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @music.artist %>
</p>

<p>
  <strong>Lyric:</strong>
  <%= @music.lyric %>
</p>

<p>
  <strong>Url image:</strong>
  <%= @music.url_image %>
</p>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>